curl -X POST http://localhost:8080/players '\n'
curl -X POST http://localhost:8080/players '\n' 
curl -X POST http://localhost:8080/players '\n'
curl -X POST http://localhost:8080/players '\n'
curl -d '{"playerId":1}' -H "Content-Type: application/json"  -X POST http://localhost:8080/rooms '\n'
curl -d '{"playerId":2}' -H "Content-Type: application/json"  -X POST http://localhost:8080/rooms '\n'
curl -X POST    http://localhost:8080/players/4/rooms/2/registrations '\n'
curl -X POST    http://localhost:8080/players/3/rooms/2/registrations '\n'
